version: '3.4'

services:

    goreact:
        image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
        container_name: goreact
        command: ["/goreact","frontend"]
        ports:
            - 80:80
        networks:
            - goweb_e2e_network

    # TODO: ADD database to mock your authentication server
    # db:
    #     image: ${DB_IMAGE_NAME}:${DB_IMAGE_TAG}
    #     container_name: db
    #     user: postgres
    #     ports:
    #         - 5432:5432
    #     environment:
    #         - POSTGRES_DB=goweb_db
    #         - POSTGRES_PASSWORD=adminpw
    #     working_dir: /opt
    #     networks:
    #         - goweb_e2e_network


networks:
    goweb_e2e_network: